# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: victor013001
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: aws-serverless-challenge
# "service" is the name of this project. This will also be added to your AWS resource names.
service: send-email

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  profile: deploy-aws

functions:
  trigger:
    handler: handler.sendEmail
    role: arn:aws:iam::842676005902:role/AWSChallengeLambdaSendEmailRole
    events:
      - sqs: arn:aws:sqs:us-east-1:842676005902:CreateUserQueue
